IF(MARCOCPPBINDING_INCLUDE_DIR AND MARCOCPPBINDING_LIBRARY)
		SET(MARCOCPPBINDING_FIND_QUIETLY TRUE)
ENDIF(MARCOCPPBINDING_INCLUDE_DIR AND MARCOCPPBINDING_LIBRARY)

FIND_PATH(MARCOCPPBINDING_INCLUDE_DIR NAMES marcoCPpolo/marco.hpp marcopolo/marco.h marcopolo/node.hpp PATHS /usr/include)

FIND_LIBRARY(MARCOCPPBINDING_LIBRARY marcopolo)

IF(MARCOCPPBINDING_INCLUDE_DIR AND MARCOCPPBINDING_LIBRARY)
	IF(MARCOCPPBINDING_LIBRARY)
		SET(MARCOCPPBINDING_LIBRARIES ${MARCOCPPBINDING_LIBRARY})
		SET(MARCOCPPBINDING_FOUND TRUE)
	ENDIF(MARCOCPPBINDING_LIBRARY)
ENDIF(MARCOCPPBINDING_INCLUDE_DIR AND MARCOCPPBINDING_LIBRARY)


if (MARCOCPPBINDING_FOUND)
	if (NOT MARCOCPPBINDING_FIND_QUIETLY)
		message(STATUS "Found MARCOCPPBINDING: ${MARCOCPPBINDING_LIBRARIES}")
	endif (NOT MARCOCPPBINDING_FIND_QUIETLY)
else()
	message(STATUS "Could not find MARCOCPPBINDING libraries!")
endif (MARCOCPPBINDING_FOUND)

MARK_AS_ADVANCED(MARCOCPPBINDING_INCLUDE_DIR MARCOCPPBINDING_LIBRARY)